load("@claro-lang//:rules.bzl", "claro_binary")

claro_binary(
  name = "fix_calibration_values",
  main_file = "fix_calibration_values.claro",
  resources = {
        "inputFile": "inputText.txt",
    },
)